version: "3.9"
services:
  api:
    build: server/
    ports:
      - "4000:4000"
  web:
    build: web/
    ports:
      - "3000:3000"
  db:
    build: db/
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
